"""Hypothesis and planning-decision layer for ADR-0021.

This package exposes the full uncertainty-to-tasking decision stack:

- evidence annotations and source-object adapters
- deterministic belief update over scenario-specific hypothesis registries
- custody-health assessment with canonical ambiguity pairs
- collection-value ranking over sensor-generic candidate types
- mission-value attribution proxy and counterfactual collect simulation
- constrained optimization, heuristic policy evaluation, and
  human-in-the-loop review ledger
- planner queueing and cross-scenario portfolio allocation
- artifact-manifest and scene-availability metadata bridges
- availability-adjusted optimization, scheduler-lite, plan execution
  simulation, and baseline planning-strategy comparison

The package is deterministic, runs against committed JSON fixtures, and
does not import detector, matcher-runtime, GFW-runtime, or external SDK
modules.  See ``docs/positioning.md`` and ``docs/pivot_audit_uncertainty_to_tasking.md``
for the public-facing scope and ``docs/decisions/0021-custody-as-uncertainty-to-tasking-engine.md``
for the architectural rationale.
"""

from custody.hypotheses.artifacts import (
    ArtifactDecisionBundle,
    ArtifactEvidenceBundle,
    ArtifactKind,
    ArtifactRecord,
    artifact_record_from_mapping,
    artifact_record_to_evidence,
    artifact_records_to_evidence,
    build_decision_from_artifacts,
    bundle_to_dict,
    bundle_to_json,
    format_artifact_decision_markdown,
    format_artifact_decision_text,
    load_artifact_manifest,
)
from custody.hypotheses.availability_optimizer import (
    AvailabilityAdjustedPlanItem,
    AvailabilityOptimizationReport,
    AvailabilityOptimizedPlan,
    AvailabilityOptimizerConstraint,
    build_availability_adjusted_candidates,
    format_availability_optimizer_markdown,
    format_availability_optimizer_text,
    optimize_availability_adjusted_plan,
    report_to_json as availability_optimizer_report_to_json,
    report_to_json_object as availability_optimizer_report_to_json_object,
)
from custody.hypotheses.baseline_comparison import (
    CrossScenarioComparisonReport,
    PlanningStrategyId,
    StrategyComparisonReport,
    StrategyEvaluation,
    compare_planning_strategies,
    compare_planning_strategies_across_scenarios,
    format_comparison_markdown,
    format_comparison_text,
    format_cross_scenario_markdown,
    format_cross_scenario_text,
    report_to_dict as comparison_report_to_dict,
    report_to_json as comparison_report_to_json,
)
from custody.hypotheses.collection_value import (
    CollectionCandidate,
    CollectionRecommendation,
    CollectionValue,
    rank_collection_candidates,
)
from custody.hypotheses.counterfactual import (
    CounterfactualCollectAssessment,
    CounterfactualOutcome,
    CounterfactualReport,
    format_counterfactual_text,
    simulate_counterfactual_collects,
)
from custody.hypotheses.custody_health import (
    CustodyHealthStatus,
    HypothesisCustodyHealth,
    assess_custody_health,
)
from custody.hypotheses.decision_packet import (
    BeliefEntry,
    CollectRecommendation,
    DecisionPacket,
    SCHEMA_VERSION,
    build_decision_packet,
    format_as_json,
    format_as_markdown,
    format_as_text,
    packet_to_json_object,
)
from custody.hypotheses.efficiency_metrics import (
    EfficiencyMetric,
    EfficiencyReport,
    WorkflowMode,
    WorkflowModel,
    WorkflowStep,
    build_baseline_workflow,
    build_custody_workflow,
    compute_efficiency_metrics,
    efficiency_report_to_json_object,
    format_efficiency_markdown,
    format_efficiency_text,
)
from custody.hypotheses.evidence import (
    from_mapping,
    from_match,
    from_observation,
    from_scene,
)
from custody.hypotheses.execution_sim import (
    ExecutionOutcomePolicy,
    ExecutionSimulationReport,
    SimulatedCollectResult,
    execution_report_to_dict,
    execution_report_to_json,
    format_execution_markdown,
    format_execution_text,
    simulate_collect_result,
    simulate_plan_execution,
)
from custody.hypotheses.explain import explain_top, format_state
from custody.hypotheses.mission_value import (
    MissionValueAssessment,
    MissionValueComponent,
    MissionValueReport,
    attribute_mission_value,
    format_mission_value_markdown,
    format_mission_value_text,
    mission_value_to_json_object,
)
from custody.hypotheses.optimizer import (
    OptimizedPlan,
    PlanConstraint,
    PlanItem,
    PlanOptimizationReport,
    format_optimizer_text,
    optimize_collection_plan,
)
from custody.hypotheses.planner_queue import (
    PlannerQueue,
    PlannerQueueItem,
    PlannerQueueStatus,
    build_planner_queue,
    create_queue_item,
    format_queue_json,
    format_queue_markdown,
    format_queue_text,
    load_review_ledger_jsonl,
    record_status_from_review,
    select_latest_review_for_scenario,
)
from custody.hypotheses.planner_review import (
    PlannerReviewRecord,
    ReviewAction,
    ReviewLedgerAppendResult,
    ReviewSubject,
    append_review_record_jsonl,
    create_planner_review_record,
    create_review_subject_from_optimized_plan,
    create_review_subject_from_policy_evaluation,
    format_review_markdown,
    format_review_text,
    record_to_dict,
    record_to_json,
)
from custody.hypotheses.policy_eval import (
    PolicyDefinition,
    PolicyEvaluation,
    PolicyEvaluationReport,
    evaluate_collection_policies,
    format_policy_eval_text,
)
from custody.hypotheses.portfolio import (
    PortfolioAllocationPlan,
    PortfolioAllocationReport,
    PortfolioCandidate,
    PortfolioConstraint,
    PortfolioPlanItem,
    allocate_portfolio,
    build_portfolio_candidates,
    format_portfolio_markdown,
    format_portfolio_text,
    portfolio_report_to_json_object,
)
from custody.hypotheses.registry import (
    SCENARIO_TENNENT,
    SCENARIO_WHITSUN,
    get_hypotheses,
    get_hypothesis_ids,
)
from custody.hypotheses.scene_availability import (
    AvailabilityAdjustedRecommendation,
    AvailabilityAdjustedValue,
    AvailabilityStatus,
    CollectFeasibilityAssessment,
    SceneAvailabilityCatalog,
    SceneAvailabilityRecord,
    adjust_recommendation_for_availability,
    assess_collect_feasibility,
    format_availability_markdown,
    format_availability_text,
    load_scene_availability_catalog,
    recommendation_to_dict as availability_recommendation_to_dict,
    recommendation_to_json as availability_recommendation_to_json,
    scene_record_from_mapping,
)
from custody.hypotheses.scheduler import (
    CollectionWindow,
    ScheduleConstraint,
    ScheduledCollect,
    SchedulePlan,
    ScheduleReport,
    collection_window_from_mapping,
    format_schedule_markdown,
    format_schedule_text,
    load_collection_windows,
    schedule_collects,
    schedule_report_to_dict,
    schedule_report_to_json,
)
from custody.hypotheses.types import (
    Hypothesis,
    HypothesisEvidence,
    HypothesisState,
)
from custody.hypotheses.update import update_state

__all__ = [
    "ArtifactDecisionBundle",
    "ArtifactEvidenceBundle",
    "ArtifactKind",
    "ArtifactRecord",
    "AvailabilityAdjustedPlanItem",
    "AvailabilityAdjustedRecommendation",
    "AvailabilityAdjustedValue",
    "AvailabilityOptimizationReport",
    "AvailabilityOptimizedPlan",
    "AvailabilityOptimizerConstraint",
    "AvailabilityStatus",
    "BeliefEntry",
    "CollectFeasibilityAssessment",
    "CollectRecommendation",
    "CollectionCandidate",
    "CollectionWindow",
    "CrossScenarioComparisonReport",
    "CollectionRecommendation",
    "CollectionValue",
    "CounterfactualCollectAssessment",
    "CounterfactualOutcome",
    "CounterfactualReport",
    "CustodyHealthStatus",
    "DecisionPacket",
    "EfficiencyMetric",
    "EfficiencyReport",
    "ExecutionOutcomePolicy",
    "ExecutionSimulationReport",
    "Hypothesis",
    "HypothesisCustodyHealth",
    "HypothesisEvidence",
    "HypothesisState",
    "MissionValueAssessment",
    "MissionValueComponent",
    "MissionValueReport",
    "OptimizedPlan",
    "PlanConstraint",
    "PlanItem",
    "PlanOptimizationReport",
    "PlannerQueue",
    "PlannerQueueItem",
    "PlannerQueueStatus",
    "PlannerReviewRecord",
    "PlanningStrategyId",
    "PolicyDefinition",
    "PolicyEvaluation",
    "PolicyEvaluationReport",
    "PortfolioAllocationPlan",
    "PortfolioAllocationReport",
    "PortfolioCandidate",
    "PortfolioConstraint",
    "PortfolioPlanItem",
    "ReviewAction",
    "ReviewLedgerAppendResult",
    "ReviewSubject",
    "SCENARIO_TENNENT",
    "SCENARIO_WHITSUN",
    "SCHEMA_VERSION",
    "SceneAvailabilityCatalog",
    "SceneAvailabilityRecord",
    "ScheduleConstraint",
    "SchedulePlan",
    "ScheduleReport",
    "ScheduledCollect",
    "SimulatedCollectResult",
    "StrategyComparisonReport",
    "StrategyEvaluation",
    "WorkflowMode",
    "WorkflowModel",
    "WorkflowStep",
    "adjust_recommendation_for_availability",
    "artifact_record_from_mapping",
    "artifact_record_to_evidence",
    "artifact_records_to_evidence",
    "assess_collect_feasibility",
    "assess_custody_health",
    "attribute_mission_value",
    "allocate_portfolio",
    "append_review_record_jsonl",
    "availability_optimizer_report_to_json",
    "availability_optimizer_report_to_json_object",
    "availability_recommendation_to_dict",
    "availability_recommendation_to_json",
    "build_availability_adjusted_candidates",
    "build_baseline_workflow",
    "build_custody_workflow",
    "build_decision_from_artifacts",
    "build_decision_packet",
    "build_planner_queue",
    "build_portfolio_candidates",
    "bundle_to_dict",
    "bundle_to_json",
    "collection_window_from_mapping",
    "compare_planning_strategies",
    "compare_planning_strategies_across_scenarios",
    "comparison_report_to_dict",
    "comparison_report_to_json",
    "create_planner_review_record",
    "create_queue_item",
    "create_review_subject_from_optimized_plan",
    "create_review_subject_from_policy_evaluation",
    "compute_efficiency_metrics",
    "efficiency_report_to_json_object",
    "evaluate_collection_policies",
    "execution_report_to_dict",
    "execution_report_to_json",
    "explain_top",
    "format_artifact_decision_markdown",
    "format_artifact_decision_text",
    "format_availability_markdown",
    "format_comparison_markdown",
    "format_comparison_text",
    "format_cross_scenario_markdown",
    "format_cross_scenario_text",
    "format_availability_optimizer_markdown",
    "format_availability_optimizer_text",
    "format_availability_text",
    "format_as_json",
    "format_as_markdown",
    "format_as_text",
    "format_counterfactual_text",
    "format_efficiency_markdown",
    "format_efficiency_text",
    "format_execution_markdown",
    "format_execution_text",
    "format_mission_value_markdown",
    "format_optimizer_text",
    "format_mission_value_text",
    "format_policy_eval_text",
    "format_portfolio_markdown",
    "format_portfolio_text",
    "format_queue_json",
    "format_queue_markdown",
    "format_queue_text",
    "format_review_markdown",
    "format_review_text",
    "format_schedule_markdown",
    "format_schedule_text",
    "format_state",
    "from_mapping",
    "from_match",
    "from_observation",
    "from_scene",
    "get_hypotheses",
    "get_hypothesis_ids",
    "load_artifact_manifest",
    "load_collection_windows",
    "load_review_ledger_jsonl",
    "load_scene_availability_catalog",
    "mission_value_to_json_object",
    "optimize_availability_adjusted_plan",
    "optimize_collection_plan",
    "packet_to_json_object",
    "portfolio_report_to_json_object",
    "rank_collection_candidates",
    "record_status_from_review",
    "scene_record_from_mapping",
    "schedule_collects",
    "schedule_report_to_dict",
    "schedule_report_to_json",
    "simulate_collect_result",
    "simulate_plan_execution",
    "record_to_dict",
    "record_to_json",
    "select_latest_review_for_scenario",
    "simulate_counterfactual_collects",
    "update_state",
]
