"""Evidence Viewer manifest loader.

The Custody dashboard's Evidence Viewer panel renders the actual SAR
chip the VLM analysed for each Umbra collect plus the per-detection
bounding boxes the VLM emitted.  This module loads the committed
fixture at ``data/demo/evidence_manifest.fixture.json`` (generated by
``scripts/31_prepare_evidence_chips.py``) into frozen dataclasses.

The Evidence Viewer is Umbra-only on purpose: Sentinel rasters are not
committed in this prototype, so any Sentinel "evidence" would be
fabricated.  Sentinel remains weak-signal cueing/context elsewhere in
the dashboard.
"""
from __future__ import annotations

import json as _json
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
EVIDENCE_MANIFEST_PATH = (
    REPO_ROOT / "data" / "demo" / "evidence_manifest.fixture.json"
)


@dataclass(frozen=True)
class EvidenceDetection:
    detection_id: str
    source_id: str
    scene_id: str
    scenario_id: str
    lat: float | None
    lon: float | None
    confidence: float | None
    vessel_length_est_m: float | None
    heading_est_deg: float | None
    bbox_x1: float | None
    bbox_y1: float | None
    bbox_x2: float | None
    bbox_y2: float | None
    reasoning: str
    detector_version: str


@dataclass(frozen=True)
class EvidenceScene:
    scene_id: str
    scenario_id: str
    collection_time: str
    whitsun_event_ordinal: int | None
    raw_image_path: str
    raw_asset_url: str
    annotated_image_path: str
    annotated_asset_url: str
    image_width_px: int
    image_height_px: int
    downsample_scale: int
    source_parquet: str
    source_gec: str
    detector_version: str
    detection_count: int
    detections: tuple[EvidenceDetection, ...]


def _detection_from_mapping(rec: Mapping[str, Any]) -> EvidenceDetection:
    return EvidenceDetection(
        detection_id=str(rec.get("detection_id") or ""),
        source_id=str(rec.get("source_id") or ""),
        scene_id=str(rec.get("scene_id") or ""),
        scenario_id=str(rec.get("scenario_id") or ""),
        lat=_maybe_float(rec.get("lat")),
        lon=_maybe_float(rec.get("lon")),
        confidence=_maybe_float(rec.get("confidence")),
        vessel_length_est_m=_maybe_float(rec.get("vessel_length_est_m")),
        heading_est_deg=_maybe_float(rec.get("heading_est_deg")),
        bbox_x1=_maybe_float(rec.get("bbox_x1")),
        bbox_y1=_maybe_float(rec.get("bbox_y1")),
        bbox_x2=_maybe_float(rec.get("bbox_x2")),
        bbox_y2=_maybe_float(rec.get("bbox_y2")),
        reasoning=str(rec.get("reasoning") or ""),
        detector_version=str(rec.get("detector_version") or ""),
    )


def _scene_from_mapping(rec: Mapping[str, Any]) -> EvidenceScene:
    detections = tuple(
        _detection_from_mapping(d) for d in (rec.get("detections") or ())
    )
    scenario_id = rec.get("scenario_id")
    if scenario_id not in ("whitsun", "tennent"):
        raise ValueError(
            f"scenario_id must be 'whitsun' or 'tennent'; got {scenario_id!r}"
        )
    return EvidenceScene(
        scene_id=str(rec.get("scene_id") or ""),
        scenario_id=str(scenario_id),
        collection_time=str(rec.get("collection_time") or ""),
        whitsun_event_ordinal=(
            int(rec["whitsun_event_ordinal"])
            if rec.get("whitsun_event_ordinal") is not None else None
        ),
        raw_image_path=str(rec.get("raw_image_path") or ""),
        raw_asset_url=str(rec.get("raw_asset_url") or ""),
        annotated_image_path=str(rec.get("annotated_image_path") or ""),
        annotated_asset_url=str(rec.get("annotated_asset_url") or ""),
        image_width_px=int(rec.get("image_width_px") or 0),
        image_height_px=int(rec.get("image_height_px") or 0),
        downsample_scale=int(rec.get("downsample_scale") or 1),
        source_parquet=str(rec.get("source_parquet") or ""),
        source_gec=str(rec.get("source_gec") or ""),
        detector_version=str(rec.get("detector_version") or ""),
        detection_count=int(rec.get("detection_count") or 0),
        detections=detections,
    )


def _maybe_float(v) -> float | None:
    if v is None:
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def load_evidence_manifest(
    path: str | Path | None = None,
) -> tuple[EvidenceScene, ...]:
    """Load the committed Evidence Viewer manifest into ``EvidenceScene``s."""
    p = Path(path) if path is not None else EVIDENCE_MANIFEST_PATH
    payload = _json.loads(p.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError(f"evidence manifest at {p} is not an object")
    scenes = payload.get("scenes")
    if not isinstance(scenes, list):
        raise ValueError(
            f"evidence manifest at {p} missing 'scenes' list"
        )
    return tuple(_scene_from_mapping(s) for s in scenes)


def evidence_scenes_for_scenario(
    scenes: Iterable[EvidenceScene],
    scenario_id: str,
) -> tuple[EvidenceScene, ...]:
    return tuple(s for s in scenes if s.scenario_id == scenario_id)


def evidence_scene_for_whitsun_event_ordinal(
    scenes: Iterable[EvidenceScene],
    current_ordinal: int,
) -> EvidenceScene | None:
    """Return the Whitsun evidence scene whose reveal ordinal is the
    largest one ``<= current_ordinal``.  Returns ``None`` until the
    first Whitsun-trace evidence scene becomes visible."""
    candidates = [
        s for s in scenes
        if s.scenario_id == "whitsun"
        and s.whitsun_event_ordinal is not None
        and s.whitsun_event_ordinal <= current_ordinal
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda s: s.whitsun_event_ordinal or 0)
    return candidates[-1]
